### ISSUE TITLE
How can i swipe the view programmatically?

### ISSUE THREAD

**Issue by lvaizer** [Tunous/SwipeActionView#14]
I want to show the user for the first time that the view is swipeable, how can i do that?

**Comment by Tunous** [comment]
This is not possible currently. A potential solution has been mentioned in https://github.com/Tunous/SwipeActionView/issues/11#issuecomment-327202307 (which could also have parameter specifying whether it should be animated) but it was never implemented. I can't promise when I could add that feature but I'm open to pull requests.

**Comment by lvaizer** [comment]
Thanks, i cant create pull request, access denied..
That's what i have added to SwipeActionView class:
`  /**
     * Move the view to its right child position.
     */
    fun moveToRightPosition() {
        moveToRightPosition(0)
    }

    /**
     * Move the view to its left child position.
     */
    fun moveToLeftPosition() {
        moveToLeftPosition(0)
    }

    /**
     * Move the view to its right child position.
     *
     * @param startDelay
     * The amount of delay, in milliseconds, to wait before starting the movement animation.
     */
    fun moveToRightPosition(startDelay: Long) {
        animateContainer(maxRightSwipeDistance, 350, startDelay) {
            canPerformSwipeAction = true
        }
    }

    /**
     * Move the view to its left child position.
     *
     * @param startDelay
     * The amount of delay, in milliseconds, to wait before starting the movement animation.
     */
    fun moveToLeftPosition(startDelay: Long) {
        animateContainer(maxLeftSwipeDistance, 350, startDelay) {
            canPerformSwipeAction = true
        }
    }`

**Comment by Tunous** [comment]
> Thanks, i cant create pull request, access denied..

This could happen if you tried to push changes to my repository instead of your own fork. Generally to be able to submit pull requests you first have to [fork](https://help.github.com/en/articles/fork-a-repo) the repository and then create a pull request with a branch from your fork. You can learn more about creating pull requests [here](https://help.github.com/en/articles/creating-a-pull-request)

___

Anyway, I've created a pull request which implements suggested feature based on your code snipped. If you want you can test it before next version is released by using a snapshot pointing to the pull request branch:

```
implementation 'com.github.Tunous:SwipeActionView:feature~swipe-from-code-SNAPSHOT'
```

If you test it please let me know if what I implemented works for you.
